inscripcion_matricula/app_alumnos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_alumnos, AlumnoListView, AlumnoCreateView, \
    AlumnoUpdateView, AlumnoDeleteView, AlumnoDetailView



app_name = 'app_alumnos'

# barra invertida para salto de línea
urlpatterns = [
    path('', login_required(index_alumnos), name='index_alumnos'),
    path('nuevo/', login_required(AlumnoCreateView.as_view()), name='nuevo'),
    path('listado/', login_required(AlumnoListView.as_view()), name='listado'),
    path('detalles/<int:pk>/', login_required(AlumnoDetailView.as_view()), name='detalles'),
    path('editar/<int:pk>/', login_required(AlumnoUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(AlumnoDeleteView.as_view()), name='borrar'),
]

inscripcion_matricula/app_usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_usuarios, Registro_usuario, EncargadoListView

app_name = 'app_usuarios'

urlpatterns = [
    path('index', login_required(index_usuarios), name='index_usuarios'),
    path('nuevo', login_required(Registro_usuario.as_view()), name='nuevo'),
    path('listado', login_required(EncargadoListView.as_view()), name='listado'),
]

inscripcion_matricula/inscripcion_matricula/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_alumnos.urls')),
    path('docentes/', include('app_docentes.urls')),
    path('encargados/', include('app_encargados.urls')),
    path('usuarios/', include('app_usuarios.urls')),
]

inscripcion_matricula/app_usuarios/models.py
from django.db import models

inscripcion_matricula/app_usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .form import Registro_form

# Create your views here.
def index_usuarios(request):
    return render(request, 'index_principal_usuarios.html')

class Registro_usuario(CreateView):
    model = User
    template_name = 'CRUD_usuarios.html'
    form_class = Registro_form
    success_url = reverse_lazy('app_usuarios:index_usuarios')

class EncargadoListView(ListView):
    model = User
    template_name = 'listado_usuarios.html'

inscripcion_matricula/app_usuarios/templates/CRUD_usuarios.html
{% extends 'index_principal_usuarios.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extraheader %}
{% endblock %}
  
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h3 class="card-title"><i class="fas fa-user"></i> Registre aquí los Usuarios</h3>
        </div>
        <div class="card-body">
          {% crispy form %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

inscripcion_matricula/app_usuarios/templates/index_principal_usuarios.html
{% extends 'base/base.html' %}

{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<hr>
<br>
<br>
    <div class="row">
        <!-- Menú lateral -->
        <div class="col-md-3">
            <ul class="card p-2">
                <li class="list-group-item">
                    <a href="{% url 'app_usuarios:index_usuarios' %}" class="nav-link"><h5>Usuarios</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_usuarios:listado' %}" class="nav-link"><h5>Listado</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_usuarios:nuevo' %}" class="nav-link"><h5>Mantenimiento Usuarios </h5></a>
                </li>
            </ul>
        </div>
        

        <!-- Información -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4>Certificaciones:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Horarios</li>
                        <li class="list-group-item">Calendario de actividades</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Descarga formulario -->
        <div class="col-md-2">
            <div class="card bg-light">
                <div class="card-header text-dark text-center">
                    <h4>Descarga ficha de inscripción</h4>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-primary btn-block">Descargar</a>
                </div>
            </div>
        </div>
    </div>
<hr>
{% endblock content %}

inscripcion_matricula/app_usuarios/templates/listado_usuarios.html
{% extends 'index_principal_usuarios.html' %}
{% load static %}

{% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
{% endblock extraheader %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h4 class="card-title">Listado de Usuarios</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-condensed" id="Jtabla" cellspacing="0" width="100%">
              <thead>
                <tr class="success">
                  <th>Nombre de Usuario</th>
                  <th>Nombres</th>
                  <th>Apellidos</th>
                  <th>Email de Recuperación</th>
                  <th>Fecha de Ingreso al Sistema</th>
                </tr>
              </thead>
              <tbody>
                {% if object_list %}
                {% for usuario in object_list %}
                <tr>
                  <td>{{ usuario.username }}</td>
                  <td>{{ usuario.first_name }}</td>
                  <td>{{ usuario.last_name }}</td>
                  <td>{{ usuario.email }}</td>
                  <td>{{ usuario.last_login }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  <td colspan="5">
                    <h3 class="text-center"><strong>No hay usuarios registrados</strong></h3>
                  </td>
                </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/filtro_Jtabla_Id.js' %}"></script>
{% endblock %}