inscripcion_matricula/app_alumnos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_alumnos, AlumnoListView, AlumnoCreateView, \
    AlumnoUpdateView, AlumnoDeleteView, AlumnoDetailView



app_name = 'app_alumnos'

# barra invertida para salto de línea
urlpatterns = [
    path('', login_required(index_alumnos), name='index_alumnos'),
    path('nuevo/', login_required(AlumnoCreateView.as_view()), name='nuevo'),
    path('listado/', login_required(AlumnoListView.as_view()), name='listado'),
    path('detalles/<int:pk>/', login_required(AlumnoDetailView.as_view()), name='detalles'),
    path('editar/<int:pk>/', login_required(AlumnoUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(AlumnoDeleteView.as_view()), name='borrar'),
]

inscripcion_matricula/app_docentes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_docentes, index_secciones, \
    DocenteCreateView, DocenteListView, DocenteUpdateView, DocenteDeleteView, \
    SeccionesCreateView, SeccionesListView

app_name = 'app_docentes'


urlpatterns = [
    path('index', login_required(index_docentes), name='index_docentes'),
    path('nuevo', login_required(DocenteCreateView.as_view()), name='nuevo'),
    path('listado', login_required(DocenteListView.as_view()), name='listado'),
    path('editar/<int:pk>/', login_required(DocenteUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(DocenteDeleteView.as_view()), name='borrar'),
    path('index_secciones', login_required(index_secciones), name='index_secciones'),
    path('nuevas_secciones', login_required(SeccionesCreateView.as_view()), name='nuevas_secciones'),
    path('listados_secciones', login_required(SeccionesListView.as_view()), name='listados_secciones'),
]

inscripcion_matricula/app_encargados/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_encargados, EncargadoListView, EncargadoCreateView

app_name = 'app_encargados'

urlpatterns = [
    path('index', login_required(index_encargados), name='index_encargados'),
    path('listado', login_required(EncargadoListView.as_view()), name='listado'),
    path('nuevo', login_required(EncargadoCreateView.as_view()), name='nuevo'),
]

inscripcion_matricula/app_usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_usuarios, Registro_usuario, EncargadoListView

app_name = 'app_usuarios'

urlpatterns = [
    path('index', login_required(index_usuarios), name='index_usuarios'),
    path('nuevo', login_required(Registro_usuario.as_view()), name='nuevo'),
    path('listado', login_required(EncargadoListView.as_view()), name='listado'),
]

inscripcion_matricula/inscripcion_matricula/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_alumnos.urls')),
    path('docentes/', include('app_docentes.urls')),
    path('encargados/', include('app_encargados.urls')),
    path('usuarios/', include('app_usuarios.urls')),
]

inscripcion_matricula/app_alumnos/models.py
from django.db import models
from datetime import datetime
from app_docentes.models import Docente

class Alumno(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=60)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    fecha_inscripcion = models.DateField(default=datetime.now)
    docente_encargado = models.ForeignKey('app_docentes.Docente', on_delete=models.SET_NULL, null=True, blank=True)
    direccion_actual = models.CharField(max_length=60, null=True, blank=True)
    telefono_actual_casa = models.CharField(max_length=60, null=True, blank=True)
    ultimo_centro_de_estudio = models.CharField(max_length=60, null=True, blank=True)
    comentarios = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nombre

inscripcion_matricula/app_alumnos/forms.py
from django import forms
from .models import Alumno

class Alumno_Form(forms.ModelForm):
    class Meta:
        model = Alumno

        fields = [
            'nombre',
            'apellido',
            'fecha_nacimiento',
            'docente_encargado',
            'direccion_actual',
            'telefono_actual_casa',
            'ultimo_centro_de_estudio',
            'comentarios',
        ]
        
        labels = {
            'nombre': 'Nombres del niño/a:',
            'apellido': 'Apellidos del niño/a:',
            'fecha_nacimiento': 'Fecha de Nacimiento:',
            'docente_encargado': 'Maestro encargado:',
            'comentarios': 'Comentarios:',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'class': 'form-control'}),
            'docente_encargado': forms.Select(attrs={'class': 'form-control'}),
            'telefono_actual_casa': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion_actual': forms.TextInput(attrs={'class': 'form-control'}),
            'ultimo_centro_de_estudio': forms.TextInput(attrs={'class': 'form-control'}),
            'comentarios': forms.Textarea(attrs={'class': 'form-control', 'cols': 3, 'rows': 3}),
        }

inscripcion_matricula/app_alumnos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import Alumno_Form
from .models import Alumno

def index_alumnos(request):
    return render(request,'index_principal.html')

class AlumnoListView(ListView):
    model = Alumno
    queryset = Alumno.objects.all()
    template_name = 'listado_alumnos.html'

class AlumnoDetailView(DetailView):
    model = Alumno
    queryset = Alumno.objects.all()
    template_name = 'detalles_alumnos.html'

class AlumnoCreateView(CreateView):
    model = Alumno
    form_class = Alumno_Form
    template_name = 'CRUD_alumnos.html'
    success_url = reverse_lazy('app_alumnos:index_alumnos')

class AlumnoUpdateView(UpdateView):
    model = Alumno
    form_class = Alumno_Form
    template_name = 'CRUD_alumnos.html'
    success_url = reverse_lazy('app_alumnos:index_alumnos')

    @method_decorator(permission_required('alumnos.change_alumno', reverse_lazy('app_alumnos:listado')))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class AlumnoDeleteView(DeleteView):
    model = Alumno
    template_name = 'eliminar_alumnos.html'
    success_url = reverse_lazy('app_alumnos:listado')


class AlumnoCreateView(CreateView):#vista basada en clases
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('app_alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    #
    #
    #VISTA PARA EDITAR LOS OBJETOS ALUMNOS
class AlumnoUpdateView(UpdateView):
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    @method_decorator(permission_required('alumnos.changue_alumno',reverse_lazy('app_alumnos:listado')))
    def dispatch(self, *args, **kwargs):
            return super(AlumnoUpdateView, self).dispatch(*args, **kwargs)
class AlumnoDeleteView(DeleteView):
    model = Alumno
    template_name = 'eliminar_alumnos.html'
    success_url =reverse_lazy('app_alumnos:listado')

inscripcion_matricula/app_alumnos/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>{% block titulo %}Inscripcion Matricula{% endblock titulo %}</title>
    
    <!-- Agrega la referencia a Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    {% block header %}
    <br>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container"> <!-- Ajusta esta clase según tu diseño -->
            <a class="navbar-brand" href="{% url 'app_alumnos:index_alumnos' %}">
                <img src="{% static 'img/inscripcion_matricula.png' %}" alt="logo Portafolio" width="200" height="75" class="logo_off">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_alumnos:index_alumnos'%}">Registro Alumnos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_docentes:index_docentes'%}">Docentes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_encargados:index_encargados'%}">Encargados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_docentes:index_secciones'%}">Secciones</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_usuarios:index_usuarios'%}">Administración de usuarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Terminar Sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>  
    <br>  
    <br>  

    {% endblock header %}

    {% block side_bar %}
    {% endblock side_bar %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

    <!-- Agrega la referencia a Bootstrap 4 JS y los scripts de jQuery y Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>