inscripcion_matricula/app_alumnos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_alumnos, AlumnoListView, AlumnoCreateView, \
    AlumnoUpdateView, AlumnoDeleteView, AlumnoDetailView



app_name = 'app_alumnos'

# barra invertida para salto de línea
urlpatterns = [
    path('', login_required(index_alumnos), name='index_alumnos'),
    path('nuevo/', login_required(AlumnoCreateView.as_view()), name='nuevo'),
    path('listado/', login_required(AlumnoListView.as_view()), name='listado'),
    path('detalles/<int:pk>/', login_required(AlumnoDetailView.as_view()), name='detalles'),
    path('editar/<int:pk>/', login_required(AlumnoUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(AlumnoDeleteView.as_view()), name='borrar'),
]

inscripcion_matricula/inscripcion_matricula/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_alumnos.urls')),
    path('docentes/', include('app_docentes.urls')),
    path('encargados/', include('app_encargados.urls')),
    path('usuarios/', include('app_usuarios.urls')),
]

inscripcion_matricula/app_alumnos/models.py
from django.db import models
from datetime import datetime
from app_docentes.models import Docente

class Alumno(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=60)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    fecha_inscripcion = models.DateField(default=datetime.now)
    docente_encargado = models.ForeignKey('app_docentes.Docente', on_delete=models.SET_NULL, null=True, blank=True)
    direccion_actual = models.CharField(max_length=60, null=True, blank=True)
    telefono_actual_casa = models.CharField(max_length=60, null=True, blank=True)
    ultimo_centro_de_estudio = models.CharField(max_length=60, null=True, blank=True)
    comentarios = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nombre

inscripcion_matricula/app_alumnos/forms.py
from django import forms
from .models import Alumno

class Alumno_Form(forms.ModelForm):
    class Meta:
        model = Alumno

        fields = [
            'nombre',
            'apellido',
            'fecha_nacimiento',
            'docente_encargado',
            'direccion_actual',
            'telefono_actual_casa',
            'ultimo_centro_de_estudio',
            'comentarios',
        ]
        
        labels = {
            'nombre': 'Nombres del niño/a:',
            'apellido': 'Apellidos del niño/a:',
            'fecha_nacimiento': 'Fecha de Nacimiento:',
            'docente_encargado': 'Maestro encargado:',
            'comentarios': 'Comentarios:',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'class': 'form-control'}),
            'docente_encargado': forms.Select(attrs={'class': 'form-control'}),
            'telefono_actual_casa': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion_actual': forms.TextInput(attrs={'class': 'form-control'}),
            'ultimo_centro_de_estudio': forms.TextInput(attrs={'class': 'form-control'}),
            'comentarios': forms.Textarea(attrs={'class': 'form-control', 'cols': 3, 'rows': 3}),
        }

inscripcion_matricula/app_alumnos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import Alumno_Form
from .models import Alumno

def index_alumnos(request):
    return render(request,'index_principal.html')

class AlumnoListView(ListView):
    model = Alumno
    queryset = Alumno.objects.all()
    template_name = 'listado_alumnos.html'

class AlumnoDetailView(DetailView):
    model = Alumno
    queryset = Alumno.objects.all()
    template_name = 'detalles_alumnos.html'

class AlumnoCreateView(CreateView):
    model = Alumno
    form_class = Alumno_Form
    template_name = 'CRUD_alumnos.html'
    success_url = reverse_lazy('app_alumnos:index_alumnos')

class AlumnoUpdateView(UpdateView):
    model = Alumno
    form_class = Alumno_Form
    template_name = 'CRUD_alumnos.html'
    success_url = reverse_lazy('app_alumnos:index_alumnos')

    @method_decorator(permission_required('alumnos.change_alumno', reverse_lazy('app_alumnos:listado')))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class AlumnoDeleteView(DeleteView):
    model = Alumno
    template_name = 'eliminar_alumnos.html'
    success_url = reverse_lazy('app_alumnos:listado')


class AlumnoCreateView(CreateView):#vista basada en clases
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('app_alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    #
    #
    #VISTA PARA EDITAR LOS OBJETOS ALUMNOS
class AlumnoUpdateView(UpdateView):
    model = Alumno#indicando el nombre del modelo a usar
    form_class = Alumno_Form#atributo form class se usa
    # para guardar el formulario que hemos creado
    template_name = 'CRUD_alumnos.html'#se coloca el templateview
    #que se va a utilizar
    success_url = reverse_lazy('alumnos:index_alumnos')#indicando la url
    #a la que volvera luego de guardado el objeto
    @method_decorator(permission_required('alumnos.changue_alumno',reverse_lazy('app_alumnos:listado')))
    def dispatch(self, *args, **kwargs):
            return super(AlumnoUpdateView, self).dispatch(*args, **kwargs)
class AlumnoDeleteView(DeleteView):
    model = Alumno
    template_name = 'eliminar_alumnos.html'
    success_url =reverse_lazy('app_alumnos:listado')

inscripcion_matricula/app_alumnos/templates/CRUD_alumnos.html
{% extends 'index_principal.html' %}

{% load static %}

{% block extraheader %}
{% endblock extraheader%}

{% block content %}
	<div class="container col-xl-10">
		<br>
		{% load crispy_forms_tags %}
		<h3 class="panel-title"><i class=""></i><center>Registro de los alumnos</center></h3>
		<hr>
		<form method="post" action="{% url 'app_alumnos:nuevo' %}">
			{% csrf_token %}
			
			<div class="row">
				<div class="col">
					{{ form.nombre | as_crispy_field }}
					{{ form.apellido | as_crispy_field }}
					{{ form.fecha_nacimiento | as_crispy_field }}
					{{ form.docente_encargado | as_crispy_field }}
					<br><br><br><br><br>
					<button type="submit" class="btn btn-primary btn-block">Guardar Registro</button>
				</div>
				<div class="col">
					{{ form.direccion_actual | as_crispy_field }}
					{{ form.telefono_actual_casa | as_crispy_field }}
					{{ form.ultimo_centro_de_estudio | as_crispy_field }}
					{{ form.comentarios | as_crispy_field }}
				</div>
			</div>		
		</form>
	</div>
	<hr>
{% endblock content %}

inscripcion_matricula/app_alumnos/templates/detalles_alumnos.html
{% extends 'index_principal.html' %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center><strong>Nombre: </strong>{{alumno.nombre}} {{alumno.apellido}} <strong>ID: </strong>{{alumno.id}}</center></h3>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_nombre">Nombre de Alumno:</label>
          <input value="{{alumno.nombre}}" type="text" class="form-control" id="id_nombre" name="nombre" placeholder="Nombre de alumno" disabled>
        </div>

        <div class="form-group">
          <label for="id_apellido">Apellido de Alumno:</label>
          <input value="{{alumno.apellido}}" type="text" class="form-control" id="id_apellido" name="apellido" placeholder="Apellido de alumno" disabled>
        </div>

        <div class="form-group">
          <label for="id_fecha_nacimiento">Fecha de Nacimiento:</label>
          <input value="{{alumno.fecha_nacimiento}}" class="form-control" type="text" id="id_fecha_nacimiento" name="fecha_nacimiento" disabled>
        </div>

        <div class="form-group">
          <label for="id_docente_encargado">Docente a Cargo:</label>
          <input value="{{alumno.docente_encargado}}" type="text" class="form-control" id="id_docente_encargado" name="docente_encargado" disabled>
        </div>
      </form>
    </div>

    <div class="col-md-6">
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_direccion_actual">Dirección del alumno:</label>
          <input value="{{alumno.direccion_actual}}" type="text" class="form-control" id="id_direccion_actual" name="direccion_actual" disabled>
        </div>

        <div class="form-group">
          <label for="id_telefono_actual_casa">Teléfono de Casa:</label>
          <input value="{{alumno.telefono_actual_casa}}" type="text" class="form-control" id="id_telefono_actual_casa" name="telefono_actual_casa" disabled>
        </div>

        <div class="form-group">
          <label for="id_ultimo_centro_de_estudio">Último Centro de Estudio:</label>
          <input value="{{alumno.ultimo_centro_de_estudio}}" type="text" class="form-control" id="id_ultimo_centro_de_estudio" name="ultimo_centro_de_estudio" disabled>
        </div>
      </form>
    </div>
  </div>

  <a href="{% url 'app_alumnos:listado'%}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Volver al listado</a>
</div>
{% endblock %}

inscripcion_matricula/app_alumnos/templates/eliminar_alumnos.html
{% extends 'index_principal.html' %}
{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<br><br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h3 class="mb-0">Eliminar Alumno</h3>
                </div>
                <div class="card-body">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <p class="card-text mt-4">
                        <strong>¿Está seguro de que desea eliminar al alumno?</strong><br>
                        Nombre: {{ alumno.nombre }} {{ alumno.apellido }}
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <button class="btn btn-danger" type="submit" value="Confirm">Sí</button>
                            <a class="btn btn-secondary" href="{% url 'app_alumnos:listado' %}">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inscripcion_matricula/app_alumnos/templates/index_principal.html
{% extends 'base/base.html' %}

{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<hr>
<br>
<br>
<div class="row">
    <!-- Menú lateral -->
    <div class="col-md-3">
        <ul class="card p-2">
            <li class="list-group-item">
                <a href="{% url 'app_alumnos:listado' %}" class="nav-link">
            <h5>Alumnos</h5>
            </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'app_alumnos:index_alumnos' %}" class="nav-link">
            <h5>Cupos de Secciones</h5>
            </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'app_alumnos:nuevo' %}" class="nav-link">
            <h5>Registrar Alumnos</h5>
            </a>
            </li>
        </ul>
    </div>



    <!-- Información -->
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h4>Requisitos de Registro:</h4>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Haber cancelado matrícula</li>
                    <li class="list-group-item">Entregar hoja llena y firmada a oficina</li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Descarga formulario -->
    <div class="col-md-2">
        <div class="card bg-light">
            <div class="card-header text-dark text-center">
                <h4>Descarga ficha de inscripción</h4>
            </div>
            <div class="card-body">
                <a href="#" class="btn btn-primary btn-block">Descargar</a>
            </div>
        </div>
    </div>
</div>
<hr>
{% endblock content %}

inscripcion_matricula/app_alumnos/templates/listado_alumnos.html
{%extends 'index_principal.html' %} 

{% load static %}

{% block extraheader %}

<link rel="stylesheet" href="{% static 'css/datatables.min.css '%}">
{% endblock extraheader %} {% block content %}

<div class="container col-sm-9">
  <div class="row">
    <div class="table-responsive ">
      <div class="panel panel-primary ">
        <div class="panel-heading">
          <h3 class="panel-title"><i class=""></i><center>Listado de Alumnos Inscritos</center></h3>
        </div>
      </div>
      <table class="table display nowrap table-responsive table-bordered table-hover table-condensed display " table id="Jtabla"  cellspacing="0" width="100  %">
        <thead>
          <tr class="success">
            <th >CODIGO</th>
            <th>NOMBRE</th>
            <th>APELLIDO</th>
            <th>Fecha de Nacimiento</th>
            <th>Docente a cargo</th>
            <th>Ultimo lugar de estudios</th>
            <th>Comentarios del alumno</th>
            {% if perms.alumnos.changue_alumno %}
            <th>Editar </th>
              {% endif %}
            <th>Borrar </th>
            <th>Detalles</th>


          </tr>
        </thead>
        <tbody>
          <tr>
            {% if object_list %} {% for alumno in object_list%}
            <td> {{alumno.id}}</td>
            <td> {{alumno.nombre}}</td>
            <td> {{alumno.apellido}}</td>
            <td> {{alumno.fecha_nacimiento}}</td>
            <td> {{alumno.docente_encargado}}</td>
            <td>{{alumno.ultimo_centro_de_estudio}}</td>
            <td>{{alumno.comentarios}}</td>
            {% if perms.alumnos.changue_alumno %}
            <td>
              <a href="{% url 'app_alumnos:editar' alumno.id %}" class="btn btn-primary "><span class="glyphicon glyphicon-pencil"></span> Editar</a>
            </td>
            {% endif %}
            <td>
              <a href="{% url 'app_alumnos:borrar' alumno.id %}" class="btn btn-danger btn-destroy "><span class="glyphicon glyphicon-pencil"></span> Borrar</a>
            </td>
            <td>
              <a href="{% url 'app_alumnos:detalles' alumno.id %}" class="btn btn-info "><span class="glyphicon glyphicon-pencil"></span> Detalles</a>
            </td>
          </tr>

          {%endfor%} {%else%}
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <h3><strong>No hay registros de alumnos</strong></h3>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- <script src="{% static 'TableFilter/tablefilter.js'%}"></script> -->
<script src="{% static 'js/filtro_Jtabla_Id.js'%}"></script>

<!-- <script src="{% static 'js/fecha.js'%}"></script> -->
<!--llamando el archivo de fitro DataTables-->

{% endblock %}