inscripcion_matricula/app_alumnos/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_alumnos, AlumnoListView, AlumnoCreateView, \
    AlumnoUpdateView, AlumnoDeleteView, AlumnoDetailView



app_name = 'app_alumnos'

# barra invertida para salto de línea
urlpatterns = [
    path('', login_required(index_alumnos), name='index_alumnos'),
    path('nuevo/', login_required(AlumnoCreateView.as_view()), name='nuevo'),
    path('listado/', login_required(AlumnoListView.as_view()), name='listado'),
    path('detalles/<int:pk>/', login_required(AlumnoDetailView.as_view()), name='detalles'),
    path('editar/<int:pk>/', login_required(AlumnoUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(AlumnoDeleteView.as_view()), name='borrar'),
]

inscripcion_matricula/app_docentes/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import index_docentes, index_secciones, \
    DocenteCreateView, DocenteListView, DocenteUpdateView, DocenteDeleteView, \
    SeccionesCreateView, SeccionesListView

app_name = 'app_docentes'


urlpatterns = [
    path('index', login_required(index_docentes), name='index_docentes'),
    path('nuevo', login_required(DocenteCreateView.as_view()), name='nuevo'),
    path('listado', login_required(DocenteListView.as_view()), name='listado'),
    path('editar/<int:pk>/', login_required(DocenteUpdateView.as_view()), name='editar'),
    path('borrar/<int:pk>/', login_required(DocenteDeleteView.as_view()), name='borrar'),
    path('index_secciones', login_required(index_secciones), name='index_secciones'),
    path('nuevas_secciones', login_required(SeccionesCreateView.as_view()), name='nuevas_secciones'),
    path('listados_secciones', login_required(SeccionesListView.as_view()), name='listados_secciones'),
]

inscripcion_matricula/inscripcion_matricula/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_alumnos.urls')),
    path('docentes/', include('app_docentes.urls')),
    path('encargados/', include('app_encargados.urls')),
    path('usuarios/', include('app_usuarios.urls')),
]

inscripcion_matricula/app_docentes/models.py
from django.db import models

class Secciones(models.Model):
    opciones_turnos = (
        ('MATUTINO', 'MATUTITO'),
        ('TARDE', 'TARDE'),
        ('FIN DE SEMANA', 'FIN DE SEMANA')
    )
    turno = models.CharField(max_length=40, choices=opciones_turnos, default='MATUTITO')
    nombre_seccion = models.CharField(blank=False, max_length=30)
    cupor_por_seccion = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nombre_seccion

class Docente(models.Model):
    dui_docente = models.CharField(blank=False, max_length=30, default='')
    nombre = models.CharField(blank=False, max_length=30)
    apellido = models.CharField(blank=False, max_length=30)
    nip_docente = models.CharField(blank=False, max_length=20, null=True)
    seccion_cargo = models.ForeignKey(Secciones, null=True, blank=True, on_delete=models.SET_NULL)
    alumnos_a_cargo = models.ForeignKey('app_alumnos.Alumno', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre

inscripcion_matricula/app_docentes/forms.py
from django import forms
from .models import Docente,Secciones# importando modelo alumno


class Docente_Form(forms.ModelForm):
    class Meta:
        model=Docente

        fields = [
            'nombre',
            'apellido',
            'seccion_cargo',
            'dui_docente',
            'nip_docente',

        ]
        seccion_cargo = forms.ModelChoiceField(
        queryset=Secciones.objects.all(),  # Aquí usamos el nombre correcto del modelo 'Secciones'
        label='Sección a cargo',
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
        labels = {
            'nombre'  :'Nombre',
            'apellido' :'Apellido',
            'seccion_cargo' :'GRADO',
            'cedula':'Cedula',
            'doc_id':'Identificacón Educador',

        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido':forms.TextInput(attrs={'class':'form-control'}),
            'seccion_cargo':forms.Select(attrs={'class':'form-control'}),
            'dui_docente':forms.TextInput(attrs={'class':'form-control'}),
            'nip_docente':forms.TextInput(attrs={'class':'form-control'}),

        }


class Secciones_Form(forms.ModelForm):
    class Meta:
        model=Secciones

        fields = [
            'turno',
            'nombre_seccion',
            'cupor_por_seccion',




        ]
        labels = {
            'turno'  :'Turno',
            'nombre_seccion' :'Nombre de la Seccion',
            'cupor_por_seccion' :'Cupo de esta seccion',


        }
        widgets = {
            'turno' : forms.Select(attrs={'class':'form-control'}),
            'nombre_seccion':forms.TextInput(attrs={'class':'form-control'}),
            'cupor_por_seccion':forms.TextInput(attrs={'class':'form-control'}),

        }

inscripcion_matricula/app_docentes/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import Docente_Form, Secciones_Form
from .models import Docente, Secciones

def index_docentes(request):
    return render(request, 'index_principal_docentes.html')

class DocenteListView(ListView):
    model = Docente
    context_object_name = 'docentes'
    template_name = 'listado_docentes.html'

class DocenteCreateView(CreateView):
    model = Docente
    form_class = Docente_Form
    template_name = 'CRUD_docentes.html'
    success_url = reverse_lazy('app_docentes:index_docentes')

class DocenteUpdateView(UpdateView):
    model = Docente
    form_class = Docente_Form
    template_name = 'CRUD_docentes.html'
    success_url = reverse_lazy('app_docentes:index_docentes')

class DocenteDeleteView(DeleteView):
    model = Docente
    template_name = 'eliminar_docentes.html'
    success_url = reverse_lazy('app_docentes:listado')

def index_secciones(request):
    return render(request, 'index_principal_secciones.html')

class SeccionesListView(ListView):
    model = Secciones
    template_name = 'listado_secciones.html'

class SeccionesCreateView(CreateView):
    model = Secciones
    form_class = Secciones_Form
    template_name = 'CRUD_secciones.html'
    success_url = reverse_lazy('app_docentes:listados_secciones')

inscripcion_matricula/app_docentes/templates/CRUD_docentes.html
{% extends 'index_principal_docentes.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header bg-primary text-white">
					<h3 class="card-title"><i class="fas fa-user"></i> Registro de Docentes</h3>
				</div>
				<div class="card-body">
					<form method="post">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit" class="btn btn-primary btn-block">Guardar</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

inscripcion_matricula/app_docentes/templates/CRUD_secciones.html
{% extends 'index_principal_secciones.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-offset-1 col-md-5">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title"><i class=""></i><center>Crear Secciones</center></h3>
				</div>
			</div>
			<form method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="turno">Turno:</label>
					<select class="form-control" id="turno" name="turno">
						<option value="MATUTINO">MATUTINO</option>
						<option value="TARDE">TARDE</option>
						<option value="FIN DE SEMANA">FIN DE SEMANA</option>
					</select>
				</div>
				<br>
				<div class="form-group">
					<label for="nombre_seccion">Nombre:</label>
					<input type="text" class="form-control" id="nombre_seccion" name="nombre_seccion" placeholder="Nombre de la seccion">
				</div>
				<br>
				<div class="form-group">
					<label for="cupos_por_seccion">Cupos:</label>
					<input type="text" class="form-control" id="cupos_por_seccion" name="cupos_por_seccion" placeholder="Asignar número de cupos">
				</div>
				<br>
				<button type="submit" class="btn btn-primary">Guardar</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

inscripcion_matricula/app_docentes/templates/eliminar_docentes.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<br><br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h3 class="card-title"><i class="fas fa-user"></i> Eliminar Docente</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h4>¿Desea borrar al Docente: {{ docente.nombre }} {{ docente.apellido }}?</h4>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">Borrar</button>
                            <a href="{% url 'app_docentes:listado' %}" class="btn btn-primary">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inscripcion_matricula/app_docentes/templates/index_principal_docentes.html
{% extends 'base/base.html' %}

{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<hr>
<br>
<br>
<div class="row">
        <!-- Menú lateral -->
        <div class="col-md-3">
            <ul class="card p-2">
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:index_docentes' %}" class="nav-link"><h5>Docentes</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:listado' %}" class="nav-link"><h5>Listado</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:nuevo' %}" class="nav-link"><h5>Mantenimiento Docentes</h5></a>
                </li>                
            </ul>
        </div>
        

        <!-- Información -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4>Certificaciones:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Materias Inpartidas</li>
                        <li class="list-group-item">Diagrama Academico</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Descarga formulario -->
        <div class="col-md-2">
            <div class="card bg-light">
                <div class="card-header text-dark text-center">
                    <h4>Descarga ficha de inscripción</h4>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-primary btn-block">Descargar</a>
                </div>
            </div>
        </div>
    </div>
<hr>
{% endblock content %}

inscripcion_matricula/app_docentes/templates/index_principal_secciones.html
{% extends 'base/base.html' %}

{% load static %}

{% block extraheader %}
{% endblock extraheader %}

{% block content %}
<hr>
<br>
<br>
<div class="row">
        <!-- Menú lateral -->
        <div class="col-md-3">
            <ul class="card p-2">
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:index_secciones' %}" class="nav-link"><h5>Seccion</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:listados_secciones' %}" class="nav-link"><h5>Listado</h5></a>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'app_docentes:nuevas_secciones' %}" class="nav-link"><h5>Mantenimiento Secciones </h5></a>
                </li>
            </ul>
        </div>
        

        <!-- Información -->
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4>Certificaciones:</h4>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Horarios</li>
                        <li class="list-group-item">Calendario de actividades</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Descarga formulario -->
        <div class="col-md-2">
            <div class="card bg-light">
                <div class="card-header text-dark text-center">
                    <h4>Descarga ficha de inscripción</h4>
                </div>
                <div class="card-body">
                    <a href="#" class="btn btn-primary btn-block">Descargar</a>
                </div>
            </div>
        </div>
    </div>
<hr>
{% endblock content %}

inscripcion_matricula/app_docentes/templates/listado_docentes.html
{% extends 'index_principal_docentes.html' %}

{% load static %}

{% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
{% endblock extraheader %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fas fa-chalkboard-teacher"></i> Listado de Docentes</h3>
        </div>
      </div>
      <div class="table-responsive">
        <table id="Jtabla" class="table table-bordered table-hover table-condensed">
          <thead class="thead-light">
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Grado a cargo</th>
              <th>DUI DEL DOCENTE</th>
              <th>Opciones</th>
            </tr>
          </thead>
          <tbody>
            {% if object_list %}
            {% for docente in object_list %}
            <tr>
              <td>{{ docente.nombre }}</td>
              <td>{{ docente.apellido }}</td>
              <td>{% if docente.seccion_cargo %}{{ docente.seccion_cargo }}{% else %}-{% endif %}</td>
              <td>{{ docente.dui_docente }}</td>
              <td>
                <a href="{% url 'app_docentes:editar' docente.id %}" class="btn btn-primary"><i class="fas fa-edit"></i> Editar</a>
                <a href="{% url 'app_docentes:borrar' docente.id %}" class="btn btn-danger btn-destroy"><i class="fas fa-trash"></i> Borrar</a>
              </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
              <td colspan="5"><h3 class="text-center">No hay ningún Docente Registrado</h3></td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/filtro_Jtabla_Id.js' %}"></script>
{% endblock %}

inscripcion_matricula/app_docentes/templates/listado_secciones.html
{% extends 'index_principal_secciones.html' %}
{% load static %}

{% block extraheader %}
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
{% endblock extraheader %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h4 class="card-title">Listado de Secciones</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-condensed" id="Jtabla" cellspacing="0" width="100%">
              <thead>
                <tr class="success">
                  <th>Sección</th>
                  <th>Turno</th>
                  <th>Cupos asignados</th>
                </tr>
              </thead>
              <tbody>
                {% if object_list %}
                {% for seccion in object_list %}
                <tr>
                  <td>{{ seccion.nombre_seccion }}</td>
                  <td>{{ seccion.turno }}</td>
                  <td>{{ seccion.cupor_por_seccion }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  <td colspan="3">
                    <h3 class="text-center"><strong>No hay ninguna sección registrada</strong></h3>
                  </td>
                </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/filtro_Jtabla_Id.js' %}"></script>
{% endblock %}